project:
  type: website
  output-dir: docs

website:
  title: "Jess Butler"
  favicon: favicon.png
  google-analytics: "G-76SX760VM2"
  navbar:
    right:
      - blog.qmd
      
format:
  html:
    theme: darkly
    css: styles.css


